# Generated by Django 5.1.4 on 2024-12-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('izoh', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('bajarildi', models.BooleanField(default=False, verbose_name='Bajarildi')),
                ('sana', models.DateField(auto_now_add=True, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Reja',
                'verbose_name_plural': 'Rejalar',
            },
        ),
    ]
